import { billingSubscriptionSchema, paymentSchema, type BillingSubscription, type Payment } from '@/lib/schemas'
import { mockMembers } from '@/lib/mock-members'
import type { MemberInfo } from '@/types/membership/memberSchemas'

const rawPayments = [
  {
    id: 'pay_ana_2026_01',
    memberId: 'm-1',
    memberName: 'Ana Santos',
    description: 'Membership fee (Jan 2026)',
    cycle: 'monthly',
    periodStart: '2026-01-01',
    periodEnd: '2026-01-31',
    dueDate: '2026-01-01',
    paidAt: '2026-01-01',
    status: 'paid',
    currency: 'PHP',
    baseAmountCents: 150_000,
    convenienceFeeCents: 3_000,
    discountCents: 0,
    method: 'credit-card',
    reference: 'CC-134234',
  },
  {
    id: 'pay_ana_2026_02',
    memberId: 'm-1',
    memberName: 'Ana Santos',
    description: 'Membership fee (Feb 2026)',
    cycle: 'monthly',
    periodStart: '2026-02-01',
    periodEnd: '2026-02-28',
    dueDate: '2026-02-01',
    paidAt: null,
    status: 'upcoming',
    currency: 'PHP',
    baseAmountCents: 150_000,
    convenienceFeeCents: 3_000,
    discountCents: 0,
    method: 'credit-card',
  },
  {
    id: 'pay_carlos_2026_01',
    memberId: 'm-2',
    memberName: 'Carlos Rivera',
    description: 'Membership fee (Jan 2026)',
    cycle: 'monthly',
    periodStart: '2026-01-05',
    periodEnd: '2026-02-04',
    dueDate: '2026-01-05',
    paidAt: null,
    status: 'failed',
    currency: 'PHP',
    baseAmountCents: 80_000,
    convenienceFeeCents: 0,
    discountCents: 5_000,
    method: 'bank-transfer',
    reference: 'BT-01922',
  },
  {
    id: 'pay_maya_2026_01',
    memberId: 'm-3',
    memberName: 'Maya Rivera',
    description: 'Membership fee (Jan 2026)',
    cycle: 'monthly',
    periodStart: '2026-01-05',
    periodEnd: '2026-02-04',
    dueDate: '2026-01-05',
    paidAt: '2026-01-06',
    status: 'paid',
    currency: 'PHP',
    baseAmountCents: 80_000,
    convenienceFeeCents: 0,
    discountCents: 0,
    method: 'bank-transfer',
    reference: 'BT-01948',
  },
  {
    id: 'pay_liza_2025_12',
    memberId: 'm-4',
    memberName: 'Liza Moreno',
    description: 'Membership fee (Dec 2025)',
    cycle: 'monthly',
    periodStart: '2025-12-15',
    periodEnd: '2026-01-14',
    dueDate: '2025-12-15',
    paidAt: null,
    status: 'overdue',
    currency: 'PHP',
    baseAmountCents: 50_000,
    convenienceFeeCents: 0,
    discountCents: 0,
    method: 'gcash',
  },
  {
    id: 'pay_ana_locker_2026_01',
    memberId: 'm-1',
    memberName: 'Ana Santos',
    description: 'Locker rental (one-time)',
    cycle: 'one-time',
    dueDate: '2026-01-10',
    paidAt: '2026-01-10',
    status: 'paid',
    currency: 'PHP',
    baseAmountCents: 20_000,
    convenienceFeeCents: 0,
    discountCents: 2_000,
    method: 'cash',
    reference: 'OR-10021',
  },
] as const

export const mockPayments: Payment[] = paymentSchema.array().parse(rawPayments)

function pickFirstMemberNameFromGroup(groupId: string): string {
  const group = mockMembers.find((m) => m.id === groupId)
  const names = group?.members.map((m: MemberInfo) => m.name) ?? []
  return names.length > 1 ? `${names[0]} +${names.length - 1}` : (names[0] ?? 'Member')
}

const rawSubscriptions = [
  {
    id: 'sub_group_1',
    memberIds: ['m-1'],
    memberDisplayName: pickFirstMemberNameFromGroup('group-1'),
    cycle: 'monthly',
    amountCents: 150_000,
    currency: 'PHP',
    startDate: '2025-12-01',
    endDate: '2026-12-01',
    nextBillingDate: '2026-02-01',
    status: 'active',
  },
  {
    id: 'sub_group_2',
    memberIds: ['m-2', 'm-3'],
    memberDisplayName: pickFirstMemberNameFromGroup('group-2'),
    cycle: 'monthly',
    amountCents: 80_000,
    currency: 'PHP',
    startDate: '2026-01-05',
    endDate: '2026-04-05',
    nextBillingDate: '2026-02-05',
    status: 'active',
  },
  {
    id: 'sub_group_3',
    memberIds: ['m-4'],
    memberDisplayName: pickFirstMemberNameFromGroup('group-3'),
    cycle: 'monthly',
    amountCents: 50_000,
    currency: 'PHP',
    startDate: '2025-11-15',
    endDate: '2026-02-14',
    nextBillingDate: '2026-01-15',
    status: 'paused',
  },
] as const

export const mockSubscriptions: BillingSubscription[] = billingSubscriptionSchema.array().parse(rawSubscriptions)
