/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PostRouteImport } from './routes/post'
import { Route as HomeRouteImport } from './routes/home'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardSalesRouteImport } from './routes/dashboard/sales'
import { Route as DashboardMembershipRouteImport } from './routes/dashboard/membership'
import { Route as AuthLoginRouteImport } from './routes/auth/login'

const PostRoute = PostRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSalesRoute = DashboardSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardMembershipRoute = DashboardMembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/home': typeof HomeRoute
  '/post': typeof PostRoute
  '/auth/login': typeof AuthLoginRoute
  '/dashboard/membership': typeof DashboardMembershipRoute
  '/dashboard/sales': typeof DashboardSalesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/home': typeof HomeRoute
  '/post': typeof PostRoute
  '/auth/login': typeof AuthLoginRoute
  '/dashboard/membership': typeof DashboardMembershipRoute
  '/dashboard/sales': typeof DashboardSalesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/home': typeof HomeRoute
  '/post': typeof PostRoute
  '/auth/login': typeof AuthLoginRoute
  '/dashboard/membership': typeof DashboardMembershipRoute
  '/dashboard/sales': typeof DashboardSalesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/about'
    | '/home'
    | '/post'
    | '/auth/login'
    | '/dashboard/membership'
    | '/dashboard/sales'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/about'
    | '/home'
    | '/post'
    | '/auth/login'
    | '/dashboard/membership'
    | '/dashboard/sales'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/about'
    | '/home'
    | '/post'
    | '/auth/login'
    | '/dashboard/membership'
    | '/dashboard/sales'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  HomeRoute: typeof HomeRoute
  PostRoute: typeof PostRoute
  AuthLoginRoute: typeof AuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/post': {
      id: '/post'
      path: '/post'
      fullPath: '/post'
      preLoaderRoute: typeof PostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/sales': {
      id: '/dashboard/sales'
      path: '/sales'
      fullPath: '/dashboard/sales'
      preLoaderRoute: typeof DashboardSalesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/membership': {
      id: '/dashboard/membership'
      path: '/membership'
      fullPath: '/dashboard/membership'
      preLoaderRoute: typeof DashboardMembershipRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardMembershipRoute: typeof DashboardMembershipRoute
  DashboardSalesRoute: typeof DashboardSalesRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardMembershipRoute: DashboardMembershipRoute,
  DashboardSalesRoute: DashboardSalesRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  HomeRoute: HomeRoute,
  PostRoute: PostRoute,
  AuthLoginRoute: AuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
